fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: ## Your duoshuo_shortname, e.g. haomwei
disqus: ## Your disqus_shortname, e.g. haomwei
google_search: true ## Use Google search, true/false
baidu_search: false ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: 主頁
    directory: .
    icon: icon-home
  - page: 所有文章
    directory: archives/
    icon: icon-archive
  - page: 自介
    directory: about/
    icon: icon-about
  - page: RSS
    directory: rss.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
#  - tag
  - recent_posts
#  - recent_comments
#  - links

links:
  - title: Twitter
    url: https://twitter.com/Monoremonton
  - title: GitHub
    url: https://github.com/alemonmk
#  - title: site-name3
#    url: http://www.example3.com/
